version: '3'

services:
  librescan:
    build: .
    image: labexperimental/librescan:latest
    container_name: librescan
    ports:
      - 8080:8080
    volumes:
      - "~/LibreScanProjects:/root/LibreScanProjects"
      - "~/.librescan:/root/.librescan"
      - "./librescan:/api/librescan"
    environment:
      - FLASK_APP
      - FLASK_DEBUG
      - LS_DEV_MODE
    command: flask run -h 0.0.0.0 -p 8080
