version: '3'

services:
  librescan:
    build: .
    image: labexperimental/librescan:latest
    container_name: librescan
    ports:
      - 8080:8080
    volumes:
      - "~/LibreScanProjects:/home/librescan/LibreScanProjects"
      - "~/.librescan:/home/librescan/.librescan"
    environment:
      - LS_DEV_MODE
