email-receiver: librescan@gmail.com
scantailor:
  l: 1.5
  margins-left: 2.5
  margins-right: 2.5
  margins-top: 2.5
  margins-bottom: 2.5
  dewarping: auto
  despeckle: off
  dpi-x: 300
  dpi-y: 300
  threshold: 0
  color-mode: black_and_white
project:
  path: /home/sd/LibreScanProjects
  last-id: 1


